steps:
- task: AzureKeyVault@1
  displayName: 'Azure Key Vault: ado-secrets'
  inputs:
    azureSubscription: 'ClientToolsInfra_670062 (88d5392f-a34f-4769-b405-f597fc533613)'
    KeyVaultName: 'ado-secrets'
    SecretsFilter: 'github-distro-mixin-password,ado-crossplatbuildscripts-password'
- powershell: |
    git clone https://$(ado-crossplatbuildscripts-password)@dev.azure.com/mssqltools/_git/CrossPlatBuildScripts
  displayName: Clone CrossPlatBuildScripts
- task: DownloadBuildArtifacts@0
  displayName: 'Download build source artifacts'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'source'
    itemPattern: '**/source.tar.gz'
    downloadPath: '$(Agent.TempDirectory)'
- task: DownloadBuildArtifacts@0
  displayName: 'Download build drop artifacts'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    itemPattern: '**/*'
    downloadPath: '$(Agent.TempDirectory)'
- task: ExtractFiles@1
  displayName: 'Extract source from build'
  inputs:
    archiveFilePatterns: '$(Agent.TempDirectory)/source/source.tar.gz'
    destinationFolder: '$(System.DefaultWorkingDirectory)/sqltoolsservice'
- task: CopyFiles@2
  displayName: 'Copy Source Files to: $(System.DefaultWorkingDirectory)/sqltoolsservice/artifacts/package'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)/drop'
    TargetFolder: '$(System.DefaultWorkingDirectory)/sqltoolsservice/artifacts/package'
# - task: PowerShell@2
#   displayName: 'Run Automated Release Script'
#   inputs:
#     filePath: '$(System.DefaultWorkingDirectory)/CrossPlatBuildScripts/AutomatedReleases/sqltoolsserviceRelease.ps1'
#     arguments: '-workspace $(System.DefaultWorkingDirectory)/sqltoolsservice -minTag v3.0.0.0 -target main -tagFormat release -isPrerelease $false -artifactsBuildId $(Build.BuildId)'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/sqltoolsservice'
#   env:
#     GITHUB_DISTRO_MIXIN_PASSWORD: $(github-distro-mixin-password)
#     ADO_CROSSPLATBUILDSCRIPTS_PASSWORD: $(ado-crossplatbuildscripts-password)

- task: PowerShell@2
  displayName: 'Package published projects'
  inputs:
    filePath: build.ps1
    arguments: '-target=dotnetpackpublished -mono'
    workingDirectory: '$(System.DefaultWorkingDirectory)/sqltoolsservice'
  continueOnError: true

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP Code Signing - Nuget Package'
  inputs:
    ConnectedServiceName: 'Code Signing'
    FolderPath: '$(System.DefaultWorkingDirectory)/sqltoolsservice/artifacts/nugetPackages'
    Pattern: '*.nupkg'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
          {
              "keyCode": "CP-401405",
              "operationSetCode": "NuGetSign",
              "parameters": [ ],
              "toolName": "sign",
              "toolVersion": "1.0"
          },
          {
              "keyCode": "CP-401405",
              "operationSetCode": "NuGetVerify",
              "parameters": [ ],
              "toolName": "sign",
              "toolVersion": "1.0"
          }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: nuget packages'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/sqltoolsservice/artifacts/nugetPackages'
    ArtifactName: 'packages'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: logs'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/sqltoolsservice/artifacts/logs'
    ArtifactName: 'logs'